/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Profile
         * @description Return the authenticated user's profile.
         *
         *     Raises 404 if the user has not completed onboarding yet.
         */
        get: operations["get_my_profile_api_v1_profiles_me_get"];
        /**
         * Upsert My Profile
         * @description Create or update the authenticated user's profile.
         *
         *     Creates a new profile on first call; updates all fields on subsequent calls.
         */
        put: operations["upsert_my_profile_api_v1_profiles_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List analyses for current user
         * @description Return analyses for the authenticated user in reverse chronological order.
         *
         *     Supports pagination via ``limit`` and ``offset`` query parameters.
         */
        get: operations["list_analyses_api_v1_analyses_get"];
        put?: never;
        /**
         * Create analysis and get signed upload URL
         * @description Create a new analysis record and return a TUS signed upload URL.
         *
         *     The client uses the returned ``upload_url`` to upload the video directly
         *     to Supabase Storage (TUS protocol). FastAPI never handles video bytes.
         *
         *     After uploading, call ``POST /analyses/{id}/start`` to begin processing.
         */
        post: operations["create_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start analysis processing
         * @description Enqueue the CV pipeline job for an uploaded analysis.
         *
         *     The analysis must be in ``queued`` status and owned by the authenticated user.
         *     Transitions status to ``quality_gate_pending`` and enqueues the ARQ worker.
         */
        post: operations["start_analysis_api_v1_analyses__analysis_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll analysis status
         * @description Return the current status of an analysis.
         *
         *     Used as a polling fallback when the Supabase Realtime subscription disconnects.
         *     Returns only ``id``, ``status``, and ``updated_at``.
         *
         *     Requirements: FR-RESL-13
         */
        get: operations["get_analysis_status_api_v1_analyses__analysis_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full analysis detail
         * @description Return full analysis detail including nested coaching result and rep metrics.
         */
        get: operations["get_analysis_detail_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete analysis and all artifacts
         * @description Delete an analysis record, cascaded rep_metrics and coaching_results, and Storage artifacts.
         *
         *     Requirements: FR-UPLD-10, FR-UPLD-11
         */
        delete: operations["delete_analysis_api_v1_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update analysis metadata
         * @description Update mutable fields on an analysis (currently: tags).
         *
         *     Requirements: FR-UPLD-10
         */
        patch: operations["update_analysis_api_v1_analyses__analysis_id__patch"];
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Csv
         * @description Download a specific analysis as a CSV file.
         *
         *     Returns one header row and one data row per rep.  Analysis metadata
         *     (exercise type, variant, created_at, confidence_score) is repeated on
         *     every row.  All fields from ``metrics_json`` are flattened into columns.
         *
         *     Raises:
         *         401 — missing or invalid JWT.
         *         403 — authenticated user does not own this analysis.
         *         404 — analysis does not exist.
         */
        get: operations["export_csv_api_v1_analyses__analysis_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/exercise/{exercise_type}/{exercise_variant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exercise Insights
         * @description Return per-exercise insights for the current user.
         */
        get: operations["get_exercise_insights_api_v1_insights_exercise__exercise_type___exercise_variant__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Global Insights
         * @description Return global insights across all exercises for the current user.
         */
        get: operations["get_global_insights_api_v1_insights_global_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Disable User */
        patch: operations["disable_user_api_v1_admin_users__user_id__disable_patch"];
        trace?: never;
    };
    "/api/v1/admin/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Analyses */
        get: operations["list_all_analyses_api_v1_admin_analyses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_admin_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/confidence-audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confidence Audit */
        get: operations["confidence_audit_api_v1_admin_confidence_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Delete all data for the authenticated user.
         */
        delete: operations["delete_account_api_v1_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminAnalysisResponse */
        AdminAnalysisResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Status */
            status: string;
            /** Exercise Type */
            exercise_type: string;
            /** Exercise Variant */
            exercise_variant: string;
            /** Confidence Score */
            confidence_score: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AdminUserResponse */
        AdminUserResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Height Cm */
            height_cm: number | null;
            /** Weight Kg */
            weight_kg: number | null;
            /** Age */
            age: number | null;
            /** Experience Level */
            experience_level: string | null;
            /** Analysis Count */
            analysis_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AnalysisCreate
         * @description Request body for POST /api/v1/analyses.
         *
         *     Validates exercise type, variant, filename, and file size.
         *     File size must be > 0 and <= 50 MB (FR-UPLD-16).
         */
        AnalysisCreate: {
            /**
             * Exercise Type
             * @description Exercise type: squat | bench | deadlift
             */
            exercise_type: string;
            /**
             * Exercise Variant
             * @description Exercise variant (depends on type)
             */
            exercise_variant: string;
            /**
             * Filename
             * @description Original filename of the video
             */
            filename: string;
            /**
             * File Size Bytes
             * @description File size in bytes (1 to 50 MB)
             */
            file_size_bytes: number;
        };
        /**
         * AnalysisCreateResponse
         * @description 201 response for POST /api/v1/analyses.
         */
        AnalysisCreateResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Upload Url */
            upload_url: string;
            /** Status */
            status: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * AnalysisDetail
         * @description Full analysis detail including nested coaching result and rep metrics.
         */
        AnalysisDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Exercise Type */
            exercise_type: string;
            /** Exercise Variant */
            exercise_variant: string;
            /** Confidence Score */
            confidence_score: number | null;
            /** Video Path */
            video_path: string | null;
            /** Annotated Video Path */
            annotated_video_path: string | null;
            /** Plot Path */
            plot_path: string | null;
            /** Pdf Path */
            pdf_path: string | null;
            /** Tags */
            tags: string[] | null;
            /** Quality Gate Result */
            quality_gate_result: {
                [key: string]: unknown;
            } | null;
            /** Summary Json */
            summary_json: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            coaching_result?: components["schemas"]["CoachingResultSchema"] | null;
            /**
             * Rep Metrics
             * @default []
             */
            rep_metrics: components["schemas"]["RepMetricSchema"][];
        };
        /**
         * AnalysisStartResponse
         * @description 202 response for POST /api/v1/analyses/{id}/start.
         */
        AnalysisStartResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
        };
        /**
         * AnalysisStatusResponse
         * @description 200 response for GET /api/v1/analyses/{id}/status.
         */
        AnalysisStatusResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AnalysisSummary
         * @description Analysis list item — no nested relationships.
         */
        AnalysisSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Exercise Type */
            exercise_type: string;
            /** Exercise Variant */
            exercise_variant: string;
            /** Confidence Score */
            confidence_score: number | null;
            /** Tags */
            tags: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AnalysisUpdate
         * @description Request body for PATCH /api/v1/analyses/{id}.
         */
        AnalysisUpdate: {
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * CoachingResultSchema
         * @description Nested coaching result for AnalysisDetail.
         */
        CoachingResultSchema: {
            /** Structured Output Json */
            structured_output_json: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Queue Depth */
            queue_depth: number;
            /** Worker Heartbeat */
            worker_heartbeat: boolean;
            /** Db Ok */
            db_ok: boolean;
        };
        /**
         * ProfileResponse
         * @description Response schema for GET and PUT /api/v1/profiles/me.
         */
        ProfileResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Height Cm */
            height_cm: number | null;
            /** Weight Kg */
            weight_kg: number | null;
            /** Age */
            age: number | null;
            /** Experience Level */
            experience_level: string | null;
            /** Arm Span Cm */
            arm_span_cm: number | null;
            /** Femur Length Cm */
            femur_length_cm: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProfileUpdate
         * @description Request body for PUT /api/v1/profiles/me.
         *
         *     Required fields: height_cm, weight_kg, age, experience_level (FR-PROF-02).
         *     Optional fields: arm_span_cm, femur_length_cm (FR-PROF-03).
         *     Experience level must be one of beginner/intermediate/advanced (FR-PROF-04).
         *     All numeric fields must be positive (>0).
         */
        ProfileUpdate: {
            /**
             * Height Cm
             * @description Height in centimetres
             */
            height_cm: number;
            /**
             * Weight Kg
             * @description Weight in kilograms
             */
            weight_kg: number;
            /**
             * Age
             * @description Age in years
             */
            age: number;
            /**
             * Experience Level
             * @description Training experience level
             * @enum {string}
             */
            experience_level: "beginner" | "intermediate" | "advanced";
            /**
             * Arm Span Cm
             * @description Arm span in centimetres (optional)
             */
            arm_span_cm?: number | null;
            /**
             * Femur Length Cm
             * @description Femur length in centimetres (optional)
             */
            femur_length_cm?: number | null;
        };
        /**
         * RepMetricSchema
         * @description Nested rep metric for AnalysisDetail.
         */
        RepMetricSchema: {
            /** Rep Index */
            rep_index: number;
            /** Start Frame */
            start_frame: number;
            /** End Frame */
            end_frame: number;
            /** Confidence Score */
            confidence_score: number | null;
            /** Metrics Json */
            metrics_json: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_my_profile_api_v1_profiles_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    upsert_my_profile_api_v1_profiles_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analyses_api_v1_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analysis_api_v1_analyses__analysis_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_status_api_v1_analyses__analysis_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_detail_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_analysis_api_v1_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_analysis_api_v1_analyses__analysis_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_api_v1_analyses__analysis_id__export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_insights_api_v1_insights_exercise__exercise_type___exercise_variant__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_type: string;
                exercise_variant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_global_insights_api_v1_insights_global_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_user_api_v1_admin_users__user_id__disable_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_analyses_api_v1_admin_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAnalysisResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_admin_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    confidence_audit_api_v1_admin_confidence_audit_get: {
        parameters: {
            query?: {
                threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAnalysisResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_v1_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
