"""001_initial_schema

Revision ID: 901e432196c4
Revises: 
Create Date: 2026-04-08 06:18:19.254989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '901e432196c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('exercise_type', sa.String(length=20), nullable=False),
    sa.Column('exercise_variant', sa.String(length=30), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('form_score_safety', sa.Float(), nullable=True),
    sa.Column('form_score_technique', sa.Float(), nullable=True),
    sa.Column('form_score_path_balance', sa.Float(), nullable=True),
    sa.Column('form_score_control', sa.Float(), nullable=True),
    sa.Column('form_score_overall', sa.Float(), nullable=True),
    sa.Column('video_path', sa.Text(), nullable=True),
    sa.Column('annotated_video_path', sa.Text(), nullable=True),
    sa.Column('plot_path', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_gate_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('threshold_version', sa.String(length=50), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('is_golden_dataset', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','quality_gate_pending','quality_gate_rejected','processing','coaching','completed','failed')", name='ck_analyses_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_user_created', 'analyses', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.String(length=30), nullable=True),
    sa.Column('arm_span_cm', sa.Float(), nullable=True),
    sa.Column('femur_length_cm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('coaching_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('structured_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_sources_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_trace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stream_complete', sa.Boolean(), nullable=True),
    sa.Column('cove_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index('ix_coaching_results_analysis', 'coaching_results', ['analysis_id'], unique=False)
    op.create_table('rep_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('rep_index', sa.Integer(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rep_metrics_analysis', 'rep_metrics', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rep_metrics_analysis', table_name='rep_metrics')
    op.drop_table('rep_metrics')
    op.drop_index('ix_coaching_results_analysis', table_name='coaching_results')
    op.drop_table('coaching_results')
    op.drop_table('user_profiles')
    op.drop_index('ix_analyses_user_created', table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
