import AccordionItem from "./AccordionItem";
import SectionHeading from "./SectionHeading";
import SectionLabel from "./SectionLabel";
import SectionWrapper from "./SectionWrapper";

export default function DifferentiatorsSection() {
  return (
    <SectionWrapper id="why-spelix">
      <SectionLabel>Why Spelix</SectionLabel>
      <SectionHeading>Three things no other app does.</SectionHeading>

      <div className="mt-12 grid items-start gap-10 md:grid-cols-12">
        <div className="md:col-span-7">
          <AccordionItem
            title="Every claim has a source you can read."
            defaultOpen
          >
            <p>
              Spelix generates its coaching through retrieval over a curated
              corpus of peer-reviewed biomechanics and exercise-science
              literature — systematic reviews, randomised trials, and validated
              clinical studies, each selected and approved by a
              kinesiology-qualified collaborator. When Spelix tells you
              something about your lift, it is not because a language model
              decided to say it. It is because the claim is directly grounded
              in published research that you can click through and read. Studies
              evaluating AI fitness apps against published guidelines have
              found only 8% of them provide any source reference. Spelix was
              designed from day one around the principle that ungrounded
              coaching is worse than no coaching — because it is confident noise.
            </p>
          </AccordionItem>

          <AccordionItem title="Built with a kinesiology specialist, not just a dataset.">
            <p>
              Every paper in Spelix's research corpus is reviewed and approved
              by a kinesiology-qualified B.Sc. candidate before it influences
              coaching output. The angle thresholds Spelix uses to evaluate
              your squat depth, knee tracking, and bar path were validated by a
              human expert against published biomechanics evidence — not
              generated by an AI and shipped. Most CV-based form-analysis
              systems use angle thresholds derived from population averages or
              generated algorithmically. Spelix's thresholds are anchored to
              peer-reviewed evidence and reviewed by a specialist who has
              actually read the papers behind them.
            </p>
          </AccordionItem>
          <p className="mt-2 px-1 font-sans text-sm italic text-ink-muted">
            AI coaching validated by a Kinesiology specialist (B.Sc. candidate).
            All coaching claims are grounded in peer-reviewed literature reviewed
            and curated by a qualified expert.
          </p>

          <AccordionItem title="The Coach Brain — coaching intelligence that compounds.">
            <p>
              Most AI coaching apps are static. The model they ship today is the
              model you get forever. The advice you receive in month one is the
              advice you receive in month twelve.
            </p>
            <p className="mt-4">
              Spelix is different. At the heart of the platform sits a coaching
              intelligence layer called the Coach Brain — a system that distils
              validated coaching patterns from real analysis outcomes,
              cross-referenced against the research corpus, reviewed by the
              kinesiology collaborator, and continuously refined. The Coach
              Brain does not apply generic AI reasoning to your lift. It applies
              coaching knowledge that has been tested, validated, and
              accumulated specifically for barbell athletes.
            </p>
            <p className="mt-4">
              The more lifters Spelix analyses, the more specific its coaching
              becomes. Patterns that emerge across body types, stance widths,
              and experience levels get learned, validated, and applied to
              future lifters. This is compounding coaching intelligence —
              something no other app in this category has built.
            </p>
          </AccordionItem>
        </div>

        <div className="md:col-span-5">
          <img
            src="/landing/results-screenshot.png"
            alt="Results page with the streaming coaching text and a citation tooltip expanded, showing the study title, authors, year, and DOI"
            className="w-full rounded-[40px] shadow-xl"
            loading="lazy"
          />
        </div>
      </div>
    </SectionWrapper>
  );
}
